### ISSUE TITLE
Problema nas pokebolas.

### ISSUE THREAD

**Issue by Tekadon58** [rubyserver/rubyserver#16]
Não é possivel da user nas pokebolas para capturar os pokemons
E muitos looktypes estão incorretos.

**Comment by Leohige** [comment]
As pokebolas ainda estão muito escassas, somente a poke ball normal (id 2149) está funcionando para capturar Pokémon. Os looktypes ainda não foram todos colocados no client também. Se você quiser contribuir entre no nosso discord: https://discord.gg/fnV5U6

**Comment by Leohige** [comment]
Todo o sistema de pokebolas já se encontra funcional, junto com todos os looktypes dos Pokémon de Kanto.
